### ISSUE TITLE
Add a filter functionality to the article cards

### ISSUE THREAD

**Issue by kaf-lamed-beyt** [Caleb335/year-in-review#4]
The article cards needs to be rendered on the page according the time it was added to the project inside the `article.js`

You'd write a function that filters the arrays of object based on the date that it was added.

```js
{
    date: moment("Oct 19, 2021").fromNow(),
}
```

**Comment by ramonvheerde** [comment]
Can you assign me?

**Comment by Caleb335** [comment]
Hi @ramonvheerde,

Thank you for fixing the issue. Kindly link your PR to this issue.

So I can merge it.
